name: Build/test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        java: [8, 17, 21]
        transport: [native, JDK]
        tls: [native, JDK]
      fail-fast: false
    name: JDK ${{ matrix.java }}, ${{ matrix.os }}, ${{ matrix.transport }} transport, ${{ matrix.tls }} SSL provider

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build and Install
      run: mvn clean install -DskipTests -pl pushy -am

    - name: Run Tests
      run: mvn -pl pushy test -Dtest='com.eatthepath.pushy.apns.server.TokenAuthenticationValidatingPushNotificationHandlerTest#testHandleNotificationWithMissingPayload'

    - name: Run NonDex Plugin
      run: mvn -pl pushy edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest='com.eatthepath.pushy.apns.server.TokenAuthenticationValidatingPushNotificationHandlerTest#testHandleNotificationWithMissingPayload'
      

    - name: Test with Maven
      env:
        PUSHY_TEST_TRANSPORT: ${{ matrix.transport }}
        PUSHY_TEST_SSL_PROVIDER: ${{ matrix.tls }}
      run: mvn verify -B --file pom.xml
